groups:
- name: general
    rules:
    - alert: TargetDown
    expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
    for: 10m
    labels:
        action: ticket
        severity: critical
    annotations:
        description: '{{ $value }}% or more of {{ $labels.job }} targets are down.'
        summary: Targets are down
